baseurl = "https://www.centralmoment.com/"
#baseurl = "/"
theme = "cocoa-eh-hugo-theme"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Brent Johnson"
title = "Brent Johnson"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
copyright = "Copyright © 2017 Brent Johnson"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/Brent_Johnson_head_shot_2017_small.png"
faviconfile = "img/Brent_Johnson_head_shot_2017_small.png"
highlightjs = true
progressively = true
share = true
latestpostcount = 5
github = "JohnsonBrent"
email = "brent@centralmoment.com"
linkedin = "brentjjohnson"
#twitter = "example"
#facebook = "facebook_id"
#social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName"
small_banner_logo = false

[params.colors]
identifier = "#0645AD"            # changes hyperlink link colors
identifier_dark = "#1a3152"
trivial = "#969896"                # changes blog section headers *AND* R printed results. I also like #6C6E58 (dk. gray)
foreground = "#181d2a"             # changes the R Markdown general text font color. I like #181d2a
background = "#f9f9f9"
background_dark = "#ffffe6"        # changes the background of code chunks. Tufte = #fffff8, Rstudio cobalt theme = #011e3a
code = "#969896"                   # changes LHS code chunk font color, e.g., "fish <-" and summary(cars). I also like #6C6E58 (dk. gray)
type = "#4B0082"                   # changes R commands like library()
special = "#ffcb8d"
value = "#4B0082"                  # changes values e.g., x <- 9999
statement = "#ff8e91"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]