---
title: "TMAG 59"
author: "Brent Johnson"
date: "October 26, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

On October 19 I had the pleasure of presenting at the TMAG organization's 59th semi-annual meeting.  TMAG is the [Information Technology Market Analysis Group](https://iprcorp.com/industry/)--a collection of market researchers and data scientists from technology companies (e.g., Google, Intel, FaceBook, Microsoft, etc.). 

I told a story (with my co-author Jaya Ramaprasad of Microsoft) of how Jaya and I combine a variety of data sources to produce one single estimate of Microsoft's market share in various server software categories.  No one single data source was perfect; they each had complimentary flaws (and strengths). But by using [Hierarchical Bayes](https://en.wikipedia.org/wiki/Bayesian_hierarchical_modeling) methods we can combine the sources so that their weaknesses offset. The finished HB estimates are less biased and more accurate than any one signel source on its own. The HB etimates are also more accurate than the combined, maximum likelihood estimator.

I don't have a recording available. Only the slides--which you can get by contacting me.

